[buildPlans.IosevkaCustom]
family = "Meow Code"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
one = "no-base-long-top-serif"
four = "open-serifless"
five = "oblique-flat-hook-serifless"
six = "closed-contour"
seven = "bend-serifless"
nine = "closed-contour"
zero = "long-dotted"
capital-a = "round-top-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-f = "serifless"
capital-g = "flat-bottom-serifless-capped"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifless"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "standard-serifless"
capital-q = "closed-swash"
capital-s = "bilateral-inward-serifed"
capital-t = "serifless"
capital-w = "straight-serifless"
capital-x = "straight-bilateral-motion-serifed"
capital-z = "cursive"
a = "double-storey-flat-bottom-serifless"
b = "flat-bottom-serifless"
d = "flat-bottom-serifless"
e = "rounded"
f = "serifed-crossbar-at-half-ascender-height"
g = "single-storey-earless-corner"
h = "straight-serifless"
i = "hooky"
j = "flat-hook-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "hooky"
m = "flat-top-short-leg-serifless"
n = "flat-top-straight-serifless"
p = "flat-top-serifless"
q = "flat-top-straight-serifless"
r = "flat-top-serifless"
s = "bilateral-inward-serifed"
t = "hookless"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-serifless"
x = "cursive"
y = "cursive-flat-hook-serifless"
z = "cursive"
capital-lambda = "straight-serifless"
lower-lambda = "straight-turn"
lower-pi = "diagonal-tailed"
asterisk = "turn-hex-mid"
ascii-single-quote = "straight"
number-sign = "upright-open"
ampersand = "upper-open"
at = "fourfold-solid-inner"
dollar = "open"
decorative-angle-brackets = "short"
lig-hyphen-chain = "with-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
